/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.moon.moonsrv.business.ws.protocollo.stardas;

import javax.xml.ws.Endpoint;

import org.apache.log4j.Logger;

import it.csi.moon.moonsrv.util.LoggerAccessor;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-16T15:55:01.696+02:00
 * Generated source version: 3.3.2
 *
 */

public class StardasCallbackService_StardasCallbackServiceSOAP_Server{
	
	private static final String CLASS_NAME = "StardasCallbackService_StardasCallbackServiceSOAP_Server";
	private static final Logger LOG = LoggerAccessor.getLoggerBusiness();
	
    protected StardasCallbackService_StardasCallbackServiceSOAP_Server() throws java.lang.Exception {
        LOG.info("[" + CLASS_NAME + "::StardasCallbackService_StardasCallbackServiceSOAP_Server] Starting Server");
        Object implementor = new StardasCallbackServiceSOAPImpl();
        String address = "http://www.stardas.org/";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new StardasCallbackService_StardasCallbackServiceSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000L);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
