/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.moon.moonsrv.business.ws.protocollo.stardas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.transports.http.configuration.ObjectFactory;

import it.csi.moon.moonsrv.business.ws.protocollo.stardas.type.ResultType;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-16T15:55:01.689+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.csi.it/stardas/services/StardasCallbackService", name = "StardasCallbackService")
@XmlSeeAlso({ObjectFactory.class})
public interface StardasCallbackService {

    @WebMethod(operationName = "EsitoSmistaDocumento", action = "http://www.csi.it/stardas/services/StardasCallbackService/EsitoSmistaDocumento")
    @RequestWrapper(localName = "EsitoSmistaDocumento", targetNamespace = "http://www.csi.it/stardas/services/StardasCallbackService", className = "it.csi.moon.moonsrv.business.ws.protocollo.stardas.EsitoSmistaDocumento")
    @ResponseWrapper(localName = "EsitoSmistaDocumentoResponse", targetNamespace = "http://www.csi.it/stardas/services/StardasCallbackService", className = "it.csi.moon.moonsrv.business.ws.protocollo.stardas.EsitoSmistaDocumentoResponse")
    public void esitoSmistaDocumento(
        @WebParam(name = "Esito", targetNamespace = "http://www.csi.it/stardas/services/StardasCallbackService")
        it.csi.moon.moonsrv.business.ws.protocollo.stardas.type.EsitoSmistaDocumentoType esito,
        @WebParam(mode = WebParam.Mode.OUT, name = "Esito", targetNamespace = "http://www.csi.it/stardas/services/StardasCallbackService")
        javax.xml.ws.Holder<ResultType> response
    );
}
