/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

export const EMB_SERVICE_NAME = {
  EDIT_ISTANZA: 'EDIT',
  VIEW_ISTANZA: 'VIEW',
  NEW_ISTANZA: 'NEW',
  ISTANZA: 'ISTANZA',
  ISTANZE: 'ISTANZE',
  ISTANZE_IN_LAVORAZIONE: 'IN_LAVORAZIONE',
  ISTANZE_IN_INTEGRAZIONE: 'IN_INTEGRAZIONE',
  ISTANZE_INVIATE: 'INVIATE'
};






