swagger: '2.0'
info:
  version: 1.0.0
  title: OTRS

schemes:
  - http
tags:
  - name: Ticket
paths:
  '/ticket':
    post:
      tags:
        - Ticket
      parameters:
        - in: body
          name: ticket
          description: il ticket da creare
          required: true
          schema:
            $ref: '#/definitions/TicketRequest'
      description: Create ticket
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
              $ref: '#/definitions/TicketResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: The token has been blacklisted.
        '500':
          description: Internal Server Error

definitions:
  TicketRequest:
    type: object
    properties:
      Ticket:
        $ref: '#/definitions/Ticket'
      Article:
        $ref: '#/definitions/Article'
      Attachment:
        type: array
        items: 
          $ref: '#/definitions/Attachment'
      DynamicField:
        type: array
        items: 
          $ref: '#/definitions/DynamicField'
  TicketResponse:
    type: object
    properties:
      TicketID:
        type: string
      TicketNumber:
        type: string
      ArticleID:
        type: string
      Error:
        $ref: '#/definitions/Error'
     
  Ticket:
    type: object
    properties:
      TicketID: 
        type: string
      TicketNumber: 
        type: string
      Title: 
        type: string
      Queue:  
        type: string
      Type:  
        type: string
      State:  
        type: string
      Priority:   
        type: string
      CustomerID:   
        type: string
      CustomerUser:  
        type: string
  Article:
    type: object
    properties:
      CommunicationChannel: 
        type: string
      SenderType:  
        type: string
      From:  
        type: string
      Subject:  
        type: string
      Body: 
        type: string
      ContentType:  
        type: string
  Attachment:
    type: object
    properties:
      ContentType: 
        type: string
      Filename:  
        type: string
      Content: 
        type: string
  Error:
    type: object
    properties:
      ErrorCode: 
        type: string
      ErrorMessage:
        type: string
  DynamicField:
    type: object
    properties:
      Name: 
        type: string
      Value:
        type: string      