/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


package it.csi.moon.moonsrv.business.ws.epay;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-11-16T21:29:21.573+01:00
 * Generated source version: 3.3.2
 *
 */

public class EPaywso2EntiService_EPaywso2EntiServiceSOAP_Server{

    protected EPaywso2EntiService_EPaywso2EntiServiceSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EPaywso2EntiServiceSOAPImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new EPaywso2EntiService_EPaywso2EntiServiceSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000L);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
