/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.moon.moonsrv.business.ws.epay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import it.csi.moon.moonsrv.business.ws.epay.type.EsitoAggiornaPosizioniDebitorieRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.EsitoInserimentoListaDiCaricoRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.ObjectFactory;
import it.csi.moon.moonsrv.business.ws.epay.type.ResponseType;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiAvvisiScadutiRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiNotifichePagamentoRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiRTRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiRichiesteDiRevocaRequest;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-11-16T21:29:21.563+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2entisrv", name = "EPaywso2EntiService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EPaywso2EntiService {

    @WebMethod(operationName = "EsitoInserimentoListaDiCarico", action = "http://www.csi.it/epay/epaywso/service/EsitoInserimentoListaDiCarico")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType esitoInserimentoListaDiCarico(
        @WebParam(partName = "parameters", name = "EsitoInserimentoListaDiCaricoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        EsitoInserimentoListaDiCaricoRequest parameters
    );

    @WebMethod(operationName = "EsitoAggiornaPosizioniDebitorie", action = "http://www.csi.it/epay/epaywso/service/EsitoAggiornaPosizioniDebitorie")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType esitoAggiornaPosizioniDebitorie(
        @WebParam(partName = "parameters", name = "EsitoAggiornaPosizioniDebitorieRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        EsitoAggiornaPosizioniDebitorieRequest parameters
    );

    @WebMethod(operationName = "TrasmettiRichiesteDiRevoca", action = "http://www.csi.it/epay/epaywso/service/TrasmettiRichiesteDiRevoca")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiRichiesteDiRevoca(
        @WebParam(partName = "parameters", name = "TrasmettiRichiesteDiRevocaRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        TrasmettiRichiesteDiRevocaRequest parameters
    );

    @WebMethod(operationName = "TrasmettiRT", action = "http://www.csi.it/epay/epaywso/service/TrasmettiRT")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiRT(
        @WebParam(partName = "parameters", name = "TrasmettiRTRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        TrasmettiRTRequest parameters
    );

    @WebMethod(operationName = "TrasmettiNotifichePagamento", action = "http://www.csi.it/epay/epaywso/service/TrasmettiNotifichePagamento")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiNotifichePagamento(
        @WebParam(partName = "parameters", name = "TrasmettiNotifichePagamentoRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        TrasmettiNotifichePagamentoRequest parameters
    );

    @WebMethod(operationName = "TrasmettiAvvisiScaduti", action = "http://www.csi.it/epay/epaywso/service/TrasmettiAvvisiScaduti")
    @WebResult(name = "EPaywsoServiceResponse", targetNamespace = "http://www.csi.it/epay/epaywso/types", partName = "parameters")
    public ResponseType trasmettiAvvisiScaduti(
        @WebParam(partName = "parameters", name = "TrasmettiAvvisiScadutiRequest", targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2enti/types")
        TrasmettiAvvisiScadutiRequest parameters
    );
}
