/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */

package it.csi.moon.moonsrv.business.ws.epay;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.2
  * 2021-11-16T21:29:21.577+01:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "EPaywso2EntiService",
                  wsdlLocation = "file:conf/wsdl/epay/EPaywso2EntiService.wsdl",
                  targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2entisrv")
public class EPaywso2EntiService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.csi.it/epay/epaywso/epaywso2entisrv", "EPaywso2EntiService");
    public static final QName EPaywso2EntiServiceSOAP = new QName("http://www.csi.it/epay/epaywso/epaywso2entisrv", "EPaywso2EntiServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:conf/wsdl/epay/EPaywso2EntiService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EPaywso2EntiService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:conf/wsdl/epay/EPaywso2EntiService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EPaywso2EntiService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EPaywso2EntiService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPaywso2EntiService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EPaywso2EntiService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EPaywso2EntiService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EPaywso2EntiService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EPaywso2EntiService
     */
    @WebEndpoint(name = "EPaywso2EntiServiceSOAP")
    public EPaywso2EntiService getEPaywso2EntiServiceSOAP() {
        return super.getPort(EPaywso2EntiServiceSOAP, EPaywso2EntiService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPaywso2EntiService
     */
    @WebEndpoint(name = "EPaywso2EntiServiceSOAP")
    public EPaywso2EntiService getEPaywso2EntiServiceSOAP(WebServiceFeature... features) {
        return super.getPort(EPaywso2EntiServiceSOAP, EPaywso2EntiService.class, features);
    }

}
