/*
* SPDX-FileCopyrightText: (C) Copyright 2023 C.S.I. Piemonte
*
* SPDX-License-Identifier: EUPL-1.2 */


/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.moon.moonsrv.business.ws.epay;

import org.apache.cxf.feature.Features;
//import org.apache.cxf.interceptor.InInterceptors;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import it.csi.moon.moonsrv.business.service.epay.EpayServiceCallback;
import it.csi.moon.moonsrv.business.ws.epay.type.EsitoAggiornaPosizioniDebitorieRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.EsitoInserimentoListaDiCaricoRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiAvvisiScadutiRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiNotifichePagamentoRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiRTRequest;
import it.csi.moon.moonsrv.business.ws.epay.type.TrasmettiRichiesteDiRevocaRequest;
import it.csi.moon.moonsrv.util.LoggerAccessor;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-11-16T21:29:21.498+01:00
 * Generated source version: 3.3.2
 *
 */

//@org.apache.cxf.interceptor.InInterceptors (interceptors = {"org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor" })
@javax.jws.WebService(
                      serviceName = "EPaywso2EntiService",
                      portName = "EPaywso2EntiServiceSOAP",
                      targetNamespace = "http://www.csi.it/epay/epaywso/epaywso2entisrv",
//                      wsdlLocation = "WEB-INF/classes/wsdl/epay/EPaywso2EntiService.wsdl",
                      endpointInterface = "it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService")
//@InInterceptors(interceptors = {"it.csi.moon.moonsrv.business.ws.handlers.WSSecurityInterceptor"})
//@Features(features = {"org.apache.cxf.feature.LoggingFeature", "org.apache.cxf.ws.policy.WSPolicyFeature"})
@Features(features = {"org.apache.cxf.feature.LoggingFeature"})
public class EPaywso2EntiServiceSOAPImpl implements EPaywso2EntiService {

	private static final String CLASS_NAME = "EPaywso2EntiServiceSOAPImpl";
	private static final Logger LOG = LoggerAccessor.getLoggerIntegration();
	
    @Autowired
	EpayServiceCallback epayServiceCallback;
	
	public EPaywso2EntiServiceSOAPImpl() {
		try {
			LOG.debug("["+CLASS_NAME+"::EPaywso2EntiServiceSOAPImpl] BEGIN END");
			SpringBeanAutowiringSupport.processInjectionBasedOnCurrentContext(this);
		} catch (Exception ex) {
			LOG.error("[EPaywso2EntiServiceSOAPImpl::EPaywso2EntiServiceSOAPImpl] Exception ", ex);
		}
	}
	
    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#esitoInserimentoListaDiCarico(it.csi.moon.moonsrv.business.ws.epay.EsitoInserimentoListaDiCaricoRequest parameters)*
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType esitoInserimentoListaDiCarico(EsitoInserimentoListaDiCaricoRequest parameters) {
        LOG.info("Executing operation esitoInserimentoListaDiCarico");
        System.out.println(parameters);
        try {
            it.csi.moon.moonsrv.business.ws.epay.type.ResponseType _return = null;
            return _return;
        } catch (Exception ex) {
        	LOG.error("[EPaywso2EntiServiceSOAPImpl::esitoInserimentoListaDiCarico] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#esitoAggiornaPosizioniDebitorie(it.csi.moon.moonsrv.business.ws.epay.EsitoAggiornaPosizioniDebitorieRequest parameters)*
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType esitoAggiornaPosizioniDebitorie(EsitoAggiornaPosizioniDebitorieRequest parameters) {
        LOG.info("Executing operation esitoAggiornaPosizioniDebitorie");
        System.out.println(parameters);
        try {
            it.csi.moon.moonsrv.business.ws.epay.type.ResponseType _return = null;
            return _return;
        } catch (Exception ex) {
        	LOG.debug("[EPaywso2EntiServiceSOAPImpl::esitoAggiornaPosizioniDebitorie] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#trasmettiRichiesteDiRevoca(it.csi.moon.moonsrv.business.ws.epay.TrasmettiRichiesteDiRevocaRequest parameters)*
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType trasmettiRichiesteDiRevoca(TrasmettiRichiesteDiRevocaRequest parameters) {
        LOG.info("Executing operation trasmettiRichiesteDiRevoca");
        System.out.println(parameters);
        try {
            it.csi.moon.moonsrv.business.ws.epay.type.ResponseType _return = null;
            return _return;
        } catch (Exception ex) {
        	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiRichiesteDiRevoca] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#trasmettiRT(it.csi.moon.moonsrv.business.ws.epay.TrasmettiRTRequest parameters)*
     * Serve solo se si fa la redirect diretto su PagoPA
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType trasmettiRT(TrasmettiRTRequest rt) {
        LOG.info("[EPaywso2EntiServiceSOAPImpl::trasmettiRT] BEGIN");
        try {
            if (LOG.isDebugEnabled()) {
            	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiRT] IN rt = " + rt);
            }
            return epayServiceCallback.riceviRicevutaTelematica(rt);
        } catch (Exception ex) {
        	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiRT] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#trasmettiNotifichePagamento(it.csi.moon.moonsrv.business.ws.epay.TrasmettiNotifichePagamentoRequest parameters)*
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType trasmettiNotifichePagamento(TrasmettiNotifichePagamentoRequest notifichePagamento) {
        LOG.info("[EPaywso2EntiServiceSOAPImpl::trasmettiNotifichePagamento] BEGIN");
        try {
            if (LOG.isDebugEnabled()) {
            	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiNotifichePagamento] IN notifichePagamento = " + notifichePagamento);
            }
            return epayServiceCallback.riceviNotificaPagamento(notifichePagamento);
        } catch (Exception ex) {
        	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiNotifichePagamento] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.moon.moonsrv.business.ws.epay.EPaywso2EntiService#trasmettiAvvisiScaduti(it.csi.moon.moonsrv.business.ws.epay.TrasmettiAvvisiScadutiRequest parameters)*
     */
    public it.csi.moon.moonsrv.business.ws.epay.type.ResponseType trasmettiAvvisiScaduti(TrasmettiAvvisiScadutiRequest parameters) {
        LOG.info("Executing operation trasmettiAvvisiScaduti");
        System.out.println(parameters);
        try {
            it.csi.moon.moonsrv.business.ws.epay.type.ResponseType result = null;
            return result;
        } catch (Exception ex) {
        	LOG.debug("[EPaywso2EntiServiceSOAPImpl::trasmettiAvvisiScaduti] Exception ", ex);
            throw new RuntimeException(ex);
        }
    }

}
